global using System;
global using System.Reflection;
global using BoneLib;
global using MelonLoader;
global using WeatherElectric.OBSControl.Melon;
global using BoneLib.BoneMenu;
global using BoneLib.BoneMenu.Elements;
global using UnityEngine;
global using WeatherElectric.OBSControl.Menu;
global using Object = UnityEngine.Object;